### ISSUE TITLE
Trailing comments are incorrectly linked to the following element

### ISSUE THREAD

**Issue by SimonMarquis** [square/gradle-dependencies-sorter#16]
On our large code base, we encountered the following situation (simplified):

```kotlin
dependencies {
  implementation(lib1)
  implementation(lib2) // lib2
  testImplementation(lib3)
  implementation(lib4) /* lib4 */
  api(lib5)
}
```

and the sorting process results in the following:

```kotlin
dependencies {
  /* lib4 */
  api(lib5)
 
  implementation(lib1)
  implementation(lib2)
  implementation(lib4)
 
  // lib2
  testImplementation(lib3)
}
```

The trailing comments are incorrectly linked to the following element.
Is this something simple to handle in the antlr grammar?

**Comment by autonomousapps** [comment]
Thanks for the issue. I think you have in fact tripped over an implicit assumption about how to treat comments based on their location. It's not in the grammar, but rather in the code that uses the grammar to do the sorting.

I'm not sure what the "easy" fix is for this, since the grammar does basically ignore whitespace. But it might be possible to detect that the comment is on the same line as a dependency declaration and then assume those two are related, rather than associated the comment with the _next_ declaration. (Actually, I think it's kind of the opposite. When parsing declarations, the code looks for comments that _precede_ it.) I haven't looked at the code in a while, but PRs are certainly welcome.

**Comment by SimonMarquis** [comment]
> When parsing declarations, the code looks for comments that precede it

Yes, this is exactly what is done. Which would make it impossible to distinguish "trailing" comments from the sorter.

https://github.com/square/gradle-dependencies-sorter/blob/ac671f3cb26b391fe7b9c900c76d7d550ae07d1f/sort/src/main/kotlin/com/squareup/sort/Sorter.kt#L140

If the grammar would understand the difference between trailing comments, this would be simpler to implement I guess, with something like:

```kotlin
tokens.getHiddenTokensToRight(dependency.declaration.end.tokenIndex, GradleGroovyScriptLexer.TRAILING_COMMENTS)
```

But I'm a novice at ANTLR and I don't know if this is even possible.

**Comment by autonomousapps** [comment]
I'm sure it's possible, but it's a matter of effort-vs-reward :) As an alternative, build script maintainers could prefer comments that precede declarations (I'm only half-joking here) or, _even better_, drop the comments altogether and use this API from Gradle:
```groovy
implementation("foo") {
  because "my cool comment"
}
```
That syntax is already supported by the parser _and_ it carries actual semantics, as opposed to comments, which are kind of a crapshoot.
